### ISSUE TITLE
False Positive?

### ISSUE THREAD

**Issue by matthewmurdoch** [ZJouba/ShedShield#5]
Windows Defender marks this as server Trojan warning.

**Comment by ZJouba** [comment]
Whaaat! Can you give me the Defender log output or something?

**Comment by ZJouba** [comment]
Seems it might be a `electron-builder` issue 
https://github.com/electron-userland/electron-builder/issues/4906

**Comment by matthewmurdoch** [comment]
Yep exactly that :)

**Comment by ZJouba** [comment]
Okay, I'll submit it to Microsoft

**Comment by ZJouba** [comment]
@matthewmurdoch Will you please provide me with the following details:
* Windows version
* Detection name (what was it detected as? The full name please)
* MS Defender definition version

**Comment by matthewmurdoch** [comment]
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2023/‎08/‎09
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

![2](https://github.com/ZJouba/ShedShield/assets/14326452/f015b030-edc2-48ce-bc90-f4e232b4cd67)
![3](https://github.com/ZJouba/ShedShield/assets/14326452/18c894f3-6ac9-4a6d-bf45-89b270862323)
![1](https://github.com/ZJouba/ShedShield/assets/14326452/a8a1a5f7-a5af-42ab-9197-ffdbb17579dc)

**Comment by ZJouba** [comment]
Thank you!

**Comment by ZJouba** [comment]
Seems to be good
![image](https://github.com/ZJouba/ShedShield/assets/42601911/acb7ab01-4029-4d9f-a79f-6949cb037e82)

**Comment by matthewmurdoch** [comment]
Confirmed runs without issues now :)

**Comment by ZJouba** [comment]
Noice!
