### ISSUE TITLE
Not accurate?

### ISSUE THREAD

**Issue by matthewmurdoch** [ZJouba/ShedShield#6]
We currently have loadshedding (Cape Town Zone 8) - from 2pm - on the program it said only 10pm.

Not sure if this is pure API issue or not. but ye - was working on my PC, obviously no notification - and ShedShield didnt pick up the zone actually having loadshedding.

**Comment by ZJouba** [comment]
Hey @matthewmurdoch, have you had the program running for a while? I just realised that it never checks for updates

**Comment by ZJouba** [comment]
Automatic updates from the ESP API will use up your quota very fast I think. What would you prefer, another method of automatically triggering an ESP API update or just a manual button?

**Comment by matthewmurdoch** [comment]
Good question: what about triggering on system start up?

**Comment by ZJouba** [comment]
It does pull the info whenever the app is started

**Comment by MohammedHoosen** [comment]
Hi, I'm having the same issue, also after restart it doesn't run automatically even thought I checked the option to “launch at start-up”.

Since they allow 50 requests per day, can't the app check once per hour?

**Comment by ZJouba** [comment]
@MohammedHoosen Which OS are you running? 

Checking status uses only 1 quota request but searching for an area uses 5 so users might have a bad experience if 24 of their quota is used without their knowledge. Hopefully #7 might help us out here

**Comment by ZJouba** [comment]
@matthewmurdoch should be addresses in https://github.com/ZJouba/ShedShield/releases/tag/v0.0.3-beta
@MohammedHoosen please open a new issue for the auto start
