### ISSUE TITLE
Use the unlimited eskom-calendar API for LS data

### ISSUE THREAD

**Issue by beyarkay** [ZJouba/ShedShield#7]
Hey!

This might help with some of the quota limitations as mentioned in #6. I maintain the free, unlimited and open source loadshedding API, [eskom-calendar](github.com/beyarkay/eskom-calendar) and was wondering if you'd accept a PR that adds it as an alternative source of information to ESP?

**Comment by ZJouba** [comment]
Oooh very interesting! Sure, go ahead

**Comment by ZJouba** [comment]
Hmmmm... seems your API's area names don't correspond to what ESP uses...

**Comment by beyarkay** [comment]
That is correct. There is no official naming scheme for loadshedding areas so area names from different sources wouldn't match up. I'd be open to trying to figure out a ESP name -> eskom-calendar name endpoint though? Something that would let you automatically transition from ESP names to eskom-calendar names.

**Comment by ZJouba** [comment]
I see ESP also doesn't have coordinates linked to their areas 😔. I would switch over to eskom-calendar completely if it had a coordinate lookup

**Comment by beyarkay** [comment]
Yeah coordinate lookup is the end goal, but municipalities don't hand out (or possibly, they don't even know) what geofences correspond with what loadshedding zones. It's a much needed feature though.
